# Generated by Django 6.0.1 on 2026-01-10 14:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('wallet_address', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('borrower', models.CharField(max_length=200)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=18)),
                ('annual_interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('term_months', models.IntegerField()),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('maturity_date', models.DateField()),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(default='performing', max_length=50)),
                ('token_contract', models.CharField(blank=True, max_length=128)),
                ('tx_hash', models.CharField(blank=True, max_length=200, null=True)),
                ('token_id', models.BigIntegerField(blank=True, null=True)),
                ('total_slices', models.IntegerField(default=100)),
                ('unit_price_usdc', models.DecimalField(decimal_places=2, default=100, max_digits=12)),
                ('metadata_cid', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('tokenized', models.BooleanField(default=False)),
                ('synchronized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SPV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Orbital Capital Series 01, LLC', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('private_key', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('last_synced_block', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CashflowHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tx_hash', models.CharField(max_length=200, unique=True)),
                ('block_number', models.PositiveIntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.investor')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.loan')),
            ],
            options={
                'verbose_name_plural': 'Cashflow Histories',
            },
        ),
        migrations.AddField(
            model_name='loan',
            name='spv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.spv'),
        ),
        migrations.CreateModel(
            name='InvestorPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slices_owned', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('balance_due', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('tx_hash', models.CharField(blank=True, max_length=200, null=True)),
                ('last_block_synced', models.PositiveIntegerField(default=0)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.investor')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.loan')),
            ],
            options={
                'indexes': [models.Index(fields=['investor', 'loan'], name='app_investo_investo_6f1840_idx')],
                'unique_together': {('investor', 'loan')},
            },
        ),
    ]
