"""
Django settings for rwa project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-np1=+8b3kvuu(=4-v38gia*wuw_9eagq^2$o8ta3pdkg39y3*@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'rwa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rwa.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static'



# Blockchain Settings
import os
from app.blockchain.client import NetworkConfig
AVAX_RPC_URL = os.getenv("AVAX_RPC_URL", "https://api.avax-test.network/ext/bc/C/rpc")
# This will try to get the address from the environment
USDC_ADDRESS = os.getenv("USDC_ADDRESS", "0x5425890298aed601595a70AB815c96711a31Bc65")  # Fuji USDC.e
SITE_BASE_URL = "localhost:8000" # for metadata URIs


# 1. Define your network choice (can be driven by .env)
DEFAULT_NETWORK = os.getenv("BLOCKCHAIN_NETWORK", NetworkConfig.AVALANCHE.value)

# 2. Map addresses to their respective networks
RWA_ADDRESS_MAP = {
    NetworkConfig.STELLAR.value: os.getenv("MASTER_RWA_ADDRESS_STELLAR", "0xEthAddress..."),
    NetworkConfig.AVALANCHE.value: os.getenv("MASTER_RWA_ADDRESS_FUJI", "0xAvaxAddress..."),
    NetworkConfig.LISK.value: os.getenv("MASTER_RWA_ADDRESS_LISK", "0xLiskAddress..."),
    NetworkConfig.PLUME.value: os.getenv("MASTER_RWA_ADDRESS_PLUME", "0xPlumeAddress..."),
}

# 3. This is the "Master" variable your app actually uses
# It looks up the address based on whatever DEFAULT_NETWORK is set to
MASTER_RWA_ADDRESS = RWA_ADDRESS_MAP.get(DEFAULT_NETWORK)
print(f"🔗 Using Master RWA Address: {MASTER_RWA_ADDRESS} for network: {DEFAULT_NETWORK}"   )
if not MASTER_RWA_ADDRESS:
    raise ValueError(f"No contract address configured for network: {DEFAULT_NETWORK}")

